name: Rust

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:

        runs-on: ubuntu-latest

        steps:
            - name: Install just
              run: |
                    curl -fsSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

            - uses: actions/checkout@v6
            - name: Run tests
              run: just test