name: Release Binaries
on:
  push:
    tags:
      - "v*"
jobs:
  generate:
    name: Create release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update Rust
        run: rustup update

      - name: Install just
        run: |
          curl -fsSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Clean build environment
        run: cargo clean && just clean

      - name: Build dos
        run: just build-dos

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: rustid
          path: ./*.exe

      - name: Publish binaries
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create --generate-notes ${{ github.ref }} './rustid.exe#DOS binary (rustid.exe)' './debug.exe#DOS debug binary (debug.exe)'
